### ISSUE TITLE
set mouse position

### ISSUE THREAD

**Issue by Bacsu** [ENSL/NS#12]
It isn't possible to set mouse position with m_rawinput 1.

**Comment by RGreenlees** [comment]
It looks like this can be resolved by temporarily disabling raw input when you want to show the cursor, setting its position, then re-enabling raw input on the next frame. This allows us to centre the cursor, and when combined with hiding the cursor with ShowCursor(FALSE) for the time raw input is disabled, it avoids seeing the default windows cursor flickering.

**Comment by pierow** [comment]
I don't think it's possible to do this with raw input enabled until valve fixes HL1, but the workarounds in place are adequate.
