### ISSUE TITLE
Integrate Evobot into NS module

### ISSUE THREAD

**Issue by RGreenlees** [ENSL/NS#130]
We should integrate Evobot into the NS game module for the Steam release, to provide in-built bot support for the game without needing to configure metamod. This would allow us, similar to Condition Zero, to make bot matches configurable when starting a new game.

This will help with player retention when we launch to Steam, as it may take a little while for the population to establish itself, and people will likely be turned off the game if they go to play and find nothing but empty servers. It will also give people breathing room to learn the game and not immediately get stomped on by vets.

Integrating the bot will also unlock some nice new capabilities which are more complex when trying to do it through Metamod, such as having the commander able to properly receive help requests from humans.

**Comment by pierow** [comment]
It's in 🎉!
