### ISSUE TITLE
Help tooltips are poorly optimized

### ISSUE THREAD

**Issue by pierow** [ENSL/NS#136]
The help tooltips cause a huge FPS drop, especially if there's a few of them.

**Comment by RGreenlees** [comment]
Looks like the biggest culprit is localizing strings. It's an expensive operation to look up the appropriate text in titles.txt and NS does it EVERY FRAME for no reason. It only has to be done once. Without localization the framerate jumps from 180 to 240 once round begins, so definitely worth fixing.
