### ISSUE TITLE
Uncrouched onos gets stuck at top of ladder

### ISSUE THREAD

**Issue by animelol** [ENSL/NS#28]
If the top of a func_ladder brush has the same height as the floor next to it, an onos that walks up to it gets stuck and starts climbing up into the air. It seems like the ladder is extended about 16 units. A crouched onos does not have this problem.

You can repro this by going to ns_tanith, going onos on top of chemical transport, then walking towards the ladders.

**Comment by NukemD** [comment]
This is a bug with the func_ladder entity, and there's no real fix other than to avoid making excessively large func_ladder brushes. On existing maps with the issue, it may be possible to carefully move the func_ladder entity with stripper2 (a Metamod plugin) just enough to where the player can't touch the top of the brush once they get to the top of the ladder.

Basically what happens is the player hitbox touches two faces of the func_ladder at the same time (the side and the top) and the engine tries to apply two directional forces to the player at the same time, which results in erratic movement or getting stuck.

**Comment by RGreenlees** [comment]
I wonder if it's possible in the NS game module to detect this situation (player at the very top of a ladder) and just "pop" them over the lip. They might see a small hitch, but could be better than getting stuck and frustrated

**Comment by RGreenlees** [comment]
Fix in pull request for 3.3 b7. It was caused by ladder code assuming the Onos was 64 units high when it is actually 108. By manually correcting the hull size to account for the extra height, ladders work just as reliably as every other player class.
