### ISSUE TITLE
Commander Mouse4/5

### ISSUE THREAD

**Issue by Tweadle** [ENSL/NS#34]
Mouse 4 and 5 selects in Commander view which is disruptive if you have these bound to other actions or use these keys for for push-to-talk.

**Comment by RGreenlees** [comment]
This issue seems quite deep, going right into the input modules in the SDK. Might take a while to dig this out, but the issue seems to be in the cl_dll input.cpp code, it is passing a Mouse1 code to the AvHScrollHandler when mouse 4/5 is pressed.

**Comment by pierow** [comment]
Fixed in 3.3b9.
