### ISSUE TITLE
Scoreboard causes +attack to stuck

### ISSUE THREAD

**Issue by jirikivaari** [ENSL/NS#46]
Clicking on the scoreboard can cause +attack to be stuck after closing the scoreboard until firing again or clicking on scoreboard again. Its highly annoying and happens quite often.

I believe it has something to do with SDL library that was used.

**Comment by pierow** [comment]
I think it's probably best to make it so the cursor only shows if right click is used when the scoreboard is open to prevent user error.  This is something CS:GO has done and probably some other source games.

This function may be a way of making such a change by having it trigger off of MOUSE_RIGHT only:
https://github.com/ENSL/NS/blob/611cb2a57bec2ab6a11aa972bb5133eed4327431/main/source/cl_dll/vgui_ScorePanel.cpp#L171

**Comment by pierow** [comment]
After thinking about it again, changing it to right mouse would likely cause +movement to stick for most people. This needs an actual fix or to just be removed in favor of player list.

**Comment by pierow** [comment]
Closing this for now, as both a change to make middle mouse open the mute squelch UI and mouse centering improvements have been made.
