### ISSUE TITLE
gl_picmip

### ISSUE THREAD

**Issue by GerhardK90** [ENSL/NS#56]
We should patch this out. It was abused in the past:
https://www.ensl.org/topics/105

**Comment by NukemD** [comment]
This cvar no longer works as of the Steampipe HL update in 2013.

But even if it did work, I know of two other methods to do the same thing that still do work. But then there's the issue of undetectable hacks which can also do the same and different things, so removing the cvar doesn't get anywhere.

**Comment by GerhardK90** [comment]
Could you explain these 2 methods in detail? I doubt it is useful to work on an anti cheat but we should make barrier as high as possible.

**Comment by NukemD** [comment]
I won't describe either method because it's not possible to block them with how hacked up current competitive players NS clients are. One method can be blocked with mp_consistency, but then you also remove 99% of the players on the server.

**Comment by GerhardK90** [comment]
Well I am actually concerned about this. We should start with something..  And I rather remove 99% of the players and force them to adapt than playing like that..

**Comment by NukemD** [comment]
Just run servers with mp_consistency 1 and mp_blockscripts 1 to block the most common method. The other method is so obscure and complicated that it's easier to just use hacks.

**Comment by pierow** [comment]
After testing, gl_picmip no longer has effect like NukemD said.  I'm aware of a few ways around this as it's common in other games as well and will likely be putting a few files that shouldn't be edited in the new mp_consistency 1 alongside the game dll checks, and moving the remaining stuff for competitive play to mp_consistency 2.
