### ISSUE TITLE
Remote server is down!

### ISSUE THREAD

**Issue by Ricaz** [ENSL/NS#60]
> I don't think you can just host modified contents of the executable archive on Github, and release your own binary separate from the source. What am I running?
> I should be able to tell without decompiling!

Anyway.. I just wanna play NS. The official installer causes my game to crash. This one complains it cannot connect to `176.9.125.172:80`. I'm really hoping this address once pointed to the old UW servers. No way to tell, though, because there is no source!

But please, help me play NS

**Comment by pierow** [comment]
Just use the zip release found here: https://github.com/ENSL/NS/releases

Your issue is with the launcher, which is also open source and separate, optional software: https://github.com/ENSL/NaturalLauncher

The server hosting the files for the launcher is down at the moment.
