### ISSUE TITLE
Project and solution configurations broken or problematic

### ISSUE THREAD

**Issue by pierow** [ENSL/NS#70]
There's a few configuration issues with the project and solution files that have been around either since the linux updates or since the game was open sourced. Currently only the playtest configurations are working, while the release and debug ones don't build.

I've managed to get a test configuration set up where I can debug ns.dll, but building a debug version of client.dll with visual studio makes hl.exe refuse to load it.

**Comment by pierow** [comment]
After looking over some old pre-3.2 dev builds, it appears the client.dll wasn't built with symbols back then either. I'm not sure what it'd take to get it working now.

**Comment by tankefugl** [comment]
I might be able to help on this one. However, we should introduce CI/CD on Windows for VS to ensure it stays consistent. We can use Actions for this.

Is there any additional information on when this started happening? Commit hash or some other clue?

**Comment by pierow** [comment]
The project has had this issue since I've started on it, so before this ENSL fork.  My best guess as to when this started happening is either:
A: During fmoraw's fork for linux compatibility - https://github.com/fmoraw/NS/commit/1622255eeb5caa904c65c1cc166f40e05b0ac326 . Looking at the solution configurations prior to this, they are quite different.
B: At or before the open source release.

Where I'm at right now is trying to determine A or B. There's build issues out of the box for the initial release even in VS 2010 for me so I've been looking at fixing those or just moving over the configurations from earlier to troubleshoot the current version.

I've obtained a vcxproj file for another HL mod in development currently, so if you'd like to reference that at all let me know.

I noticed that dev builds from 3.2 and prior didn't include a .pdb for the client.dll, so there may have been issues debugging that in the past, but judging from the file size of client.dll in the official 3.2 release it looks like it was built with symbols so getting HL to run a client.dll built with symbols should be possible.

**Comment by tankefugl** [comment]
Ok, that's good to know. We might be able to bisect back to see where it fails, but it might be just as easy to tackle it head-on with a reference .vcxproj file. If you can make this available or point me to it, that'd be good.

There are some issues with the VS solution files as they are right now, such as hard-coded paths. Once we identify why this debug fails and fix it, I am tempted to suggest either a CMake-based build system or to introduce environment variables in the solution to control system specific configurations.

**Comment by pierow** [comment]
I emailed you the mentioned project file since it's for a mod that isn't open source.

Here's valve's SDK. It has build errors out of the box for me:
https://github.com/ValveSoftware/halflife
An open source mod that might be of use. I haven't tried building it:
https://github.com/maxvollmer/Half-Life-VR

Regarding CMake, OpenAG a cross platform HL mod that uses it and might be a reference if we move to that:
https://github.com/YaLTeR/OpenAG

After moving the old project configuration settings over from puzl's fork I'm getting a bunch of debug code errors that weren't being found before so perhaps fixing all of those will generate something usable.

**Comment by tankefugl** [comment]
Cheers.

I am having problems running NS from develop though, without any code changes I get access violations when creating a server, even with Playtest. Investigating.

**Comment by pierow** [comment]
I see what you mean about hard-coded paths.  I was a few commits behind on my local branch  and just tried the dev branch. Gerhard committed a bunch of project files here https://github.com/ENSL/NS/commit/86740805041c0f085672c15aadfcbeb406906dd6 that might be worth reverting to the previous versions.

**Comment by jirikivaari** [comment]
I haven't really looked into the solution files as I don't use VS studio that much but there's already Makefile to make linux builds.

CMake could make visual studio project files for windows and makefiles for linux. Makefile has some changes in, so those would have to be included.
