### ISSUE TITLE
Weapons floating in air

### ISSUE THREAD

**Issue by pierow** [ENSL/NS#73]
Same issue on UWE repo: https://github.com/unknownworlds/NS/issues/3

When a player dies, the weapons dropped tends to get stuck on each other and float in the air, making it so other players can't pick them up. This seems to happen more on high tick rate servers.  Recreation for typical occurrence is to `kill` in console after equipping an HMG and welder.  This can also be recreated by dropping weapons in quick succession while looking up in the air to make them collide.

A plugin exists that searches around players when they die and uses `EF_DropToFloor`, fixing the most problematic occurrences.

**Comment by pierow** [comment]
The relevant code where the weapon is created. It might be possible to just DROP_TO_FLOOR the entity at the end of this, but would likely fall straight down instantly.
https://github.com/ENSL/NS/blob/2fb18b989f8ba369a94a3a7a80bcc14bdd1e42d9/main/source/mod/AvHPlayer.cpp#L955

Putting a delay on the welder and mines seems like it might be a good enough fix for most cases here:
https://github.com/ENSL/NS/blob/2fb18b989f8ba369a94a3a7a80bcc14bdd1e42d9/main/source/mod/AvHPlayer.cpp#L4762-L4771

Fixing the collision between weapons should fully solve the issue, but I haven't explored how to do that.

**Comment by Bacsu** [comment]
https://github.com/ENSL/NS/blob/d4e91fd005ba274701d962391d8ce5a2452ab8be/main/source/dlls/weapons.cpp#L782-L797

this has to be after line 797. It will prevent floating weapons midair and also stuck inside buildings. i.e. if you drop it on a PG. 
On the other side weapons can go through structures if you drop them.

`if(pev->solid & SOLID_BBOX)`
`{`
`pev->solid = SOLID_TRIGGER;`
`}`
