### ISSUE TITLE
Shotgun reload bugs

### ISSUE THREAD

**Issue by jirikivaari** [ENSL/NS#81]
Several shotgun bugs.

- [ ] Sometimes firing animation does not play
- [ ] Reloading forever
- [ ] Shooting while reloading causes it to shoot randomly, sometimes twice fast after a pause.

**Comment by pierow** [comment]
The biggest issue is the shotgun reload state seems to desync between the client and server and it's a common bug that trying to shoot while reloading is very inconsistent.  What seems to happen from some testing is that while reloading, the shotgun can only be fired the frame after a shell is added to the ammo count but before another shell load starts, so this can only occur while holding click and the reload animation isn't synced with the ammo count state so it appears to shoot randomly.

It's worth noting that this behavior has worked itself into part of the game's balance by allowing for a shotgunner to be somewhat vulnerable to aliens during reloads. I've been able to implement the ability to shoot at any time during the reload, but such a change would be a major balance change.

**Planned rework:**
During a shotgun reload, if the client tries to fire the shotgun, it ends the reload and does a pump animation. Once the pump animation completes the shotgun can then be fired. This would retain some of the vulnerability to reloading, but also make getting out of reload predictable and consistent.
